export const industries = [
  "restaurant",
  "ecommerce",
  "clothing",
  "school-college",
  "medical-clinic",
  "travel-tours",
  "gym-fitness",
  "real-estate",
  "beauty-salon",
  "grocery",
  "educational-consultancy",
  "digital-agency",
  "dental-clinic",
  "booking-service",
  "website-developer",
];

// Top 15 major cities for pre-rendering to optimize build size
export const MAJOR_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Lalitpur",
  "Bharatpur",
  "Biratnagar",
  "Birgunj",
  "Dharan",
  "Itahari",
  "Butwal",
  "Hetauda",
  "Janakpur",
  "Jhapa",
  "Nepalgunj",
  "Dhangadhi",
  "Bhairahawa",
  "Siddharthanagar",
  "Chitwan",
  "Nepal",
].map((c) => c.toLowerCase());

export const NEPAL_CITIES = [
  "Kathmandu",
  "Pokhara",
  "Bharatpur",
  "Lalitpur",
  "Birgunj",
  "Biratnagar",
  "Ghorahi",
  "Dhangadhi",
  "Itahari",
  "Janakpur",
  "Butwal",
  "Hetauda",
  "Tulsipur",
  "Dharan",
  "Nepalgunj",
  "Kalaiya",
  "Jitpursimara",
  "Budhanilkantha",
  "Birendranagar",
  "Tarakeshwar",
  "Tilottama",
  "Gokarneshwar",
  "Suryabinayak",
  "Chandragiri",
  "Tokha",
  "Mechinagar",
  "Kageshwari-Manohara",
  "Mahalaxmi",
  "Bhimdatta",
  "Sundar-Haraincha",
  "Madhyapur-Thimi",
  "Birtamod",
  "Nagarjun",
  "Damak",
  "Triyuga",
  "Lahan",
  "Kohalpur",
  "Godawari",
  "Banganga",
  "Siraha",
  "Barahachhetra",
  "Lamki-Chuha",
  "Ratnanagar",
  "Tikapur",
  "Kapilvastu",
  "Changunarayan",
  "Lumbini-Sanskritik",
  "Kawasoti",
  "Ghodaghodi",
  "Shivaraj",
  "Arjundhara",
  "Chandrapur",
  "Belbari",
  "Kirtipur",
  "Barahathawa",
  "Gaindakot",
  "Bhaktapur",
  "Vyas",
  "Sainamaina",
  "Bardaghat",
  "Buddhabhumi",
  "Inaruwa",
  "Gulariya",
  "Siddharthanagar",
  "Bardibas",
  "Shivasatakshi",
  "Barbardiya",
  "Gaushala",
  "Devdaha",
  "Pathari-Shanischare",
  "Sunawal",
  "Krishnapur",
  "Kamalamai",
  "Bhadrapur",
  "Urlabari",
  "Rajbiraj",
  "Dudhauli",
  "Krishnanagar",
  "Ishwarpur",
  "Banepa",
  "Khairhani",
  "Rapti",
  "Lalbandi",
  "Duhabi",
  "Maharajganj",
  "Gauriganga",
  "Ramgram",
  "Golbazar",
  "Jaleshwar",
  "Ramdhuni",
  "Bansgadhi",
  "Sabaila",
  "Punarbas",
  "Ratuwamai",
  "Madhyabindu",
  "Garuda",
  "Rajapur",
  "Gauradaha",
  "Katari",
  "Mirchaiya",
  "Mahagadhimai",
  "Bidur",
  "Lamahi",
  "Kalyanpur",
  "Nilkantha",
  "Kanchanrup",
  "Devchuli",
  "Bedkot",
  "Rangeli",
  "Baglung",
  "Sunawarshi",
  "Shuklagandaki",
  "Bhangaha",
  "Simraungadh",
  "Suryodaya",
  "Malangwa",
  "Godaita",
  "Rajpur",
  "Gujara",
  "Shuklaphanta",
  "Belauri",
  "Shahidnagar",
  "Chaudandigadhi",
  "Bhajani",
  "Dhangadimai",
  "Kankai",
  "Hanumannagar-Kankalini",
  "Khadak",
  "Gorkha",
  "Manara-Shiswa",
  "Kalika",
  "Dhanushadham",
  "Ishnath",
  "Paunauti",
  "Kolhabi",
  "Chhireshwarnath",
  "Belaka",
  "Tansen",
  "Madhuwan",
  "Waling",
  "Ilam",
  "Hariwan",
  "Brindaban",
  "Balawa",
  "Surunga",
  "Thakurbaba",
  "Gadhimai",
  "Mithila",
  "Phidim",
  "Gurbhakot",
  "Bheriganga",
  "Balara",
  "Dakneshwari",
  "Bagmati",
  "Bodebarsain",
  "Katahariya",
  "Loharpatti",
  "Paroha",
  "Hansapur",
  "Kamala",
  "Kabilasi",
  "Ganeshman-Charanath",
  "Bahudarmai",
  "Haripur",
  "Diktel-Rupakot-Majhuwagadhi",
  "Dodhara-Chandani",
  "Bhanu",
  "Chautara-Sangachokgadhi",
  "Sandhikharka",
  "Phatuwa-Bijayapur",
  "Pyuthan",
  "Sukhipur",
  "Putalibazar",
  "Parsagadhi",
  "Melamchi",
  "Madhav-Narayan",
  "Rampur",
  "Pacharauta",
  "Gaur",
  "Manthali",
  "Shambhunath",
  "Boudhimai",
  "Dullu",
  "Thaha",
  "Haripurwa",
  "Dewahi-Gonahi",
  "Karjanha",
  "Madi",
  "Puchaudi",
  "Mithila-Bihari",
  "Besisahar",
  "Letang",
  "Kushma",
  "Nagarain",
  "Bheri",
  "Chhedagad",
  "Bideha",
  "Sitganga",
  "Nijgadh",
  "Pokhariya",
  "Palungtar",
  "Aurahi",
  "Ramgopalpur",
  "Matihani",
  "Dhankuta",
  "Aathabiskot",
  "Panchapuri",
  "Rajdevi",
  "Parshuram",
  "Khandbari",
  "Panchkhal",
  "Rolpa",
  "Belkotgadhi",
  "Bhimeshwar",
  "Sharada",
  "Musikot",
  "Bagchaur",
  "Dipayal-Silgadhi",
  "Bungal",
  "Dhulikhel",
  "Bangad-Kupinde",
  "Beni",
  "Maulapur",
  "Swargadwari",
  "Lekbeshi",
  "Dasharathchand",
  "Resunga",
  "Aathabis",
  "Galyang",
  "Deumai",
  "Mai",
  "Galkot",
  "Shikhar",
  "Mandan-Deupur",
  "Dhorpatan",
  "Shadananda",
  "Shankharapur",
  "Bhimad",
  "Patan",
  "Dhunibeshi",
  "Chaurjahari",
  "Nalgad",
  "Phungling",
  "Bhumikasthan",
  "Siddhicharan",
  "Halesi-Tuwachung",
  "Sundarbazar",
  "Chainpur",
  "Chamunda-Bindrasaini",
  "Mangalsen",
  "Dakshinkali",
  "Namobuddha",
  "Narayan",
  "Panchadewal-Binayak",
  "Bhojpur",
  "Sanphebagar",
  "Solu-Dudhkunda",
  "Ramechhap",
  "Jaimini",
  "Chhayanath-Rara",
  "Amargadhi",
  "Barhabise",
  "Mahakali",
  "Saptakoshi",
  "Chapakot",
  "Bhirkot",
  "Khandachakra",
  "Mahalaxmi-Kaski",
  "Madhya-Nepal",
  "Jaya-Prithvi",
  "Shailyashikhar",
  "Chandannath",
  "Kamalbazar",
  "Melauli",
  "Phalebas",
  "Budhiganga",
  "Budhinanda",
  "Pakhribas",
  "Myanglung",
  "Badimalika",
  "Tribeni",
  "Raskot",
  "Rainas",
  "Panchkhapan",
  "Tilagupha",
  "Jiri",
  "Dharmadevi",
  "Laligurans",
  "Tripura-Sundari",
  "Thuli-Bheri",
  "Janakpurdham",
  "Jhapa",
  "Khotang",
  "Morang",
  "Okhaldhunga",
  "Panchthar",
  "Sankhuwasabha",
  "Solukhumbu",
  "Sunsari",
  "Taplejung",
  "Terhathum",
  "Udayapur",
  "Bara",
  "Dhanusha",
  "Mahottari",
  "Parsa",
  "Rautahat",
  "Saptari",
  "Sarlahi",
  "Chitwan",
  "Dhading",
  "Dolakha",
  "Kavrepalanchok",
  "Makwanpur",
  "Nuwakot",
  "Rasuwa",
  "Sindhuli",
  "Sindhupalchok",
  "Kaski",
  "Lamjung",
  "Manang",
  "Mustang",
  "Myagdi",
  "Nawalpur",
  "Parbat",
  "Syangja",
  "Tanahun",
  "Arghakhanchi",
  "Banke",
  "Bardiya",
  "Dang",
  "Gulmi",
  "Parasi",
  "Palpa",
  "Rupandehi",
  "East-Rukum",
  "West-Rukum",
  "Dailekh",
  "Dolpa",
  "Humla",
  "Jajarkot",
  "Jumla",
  "Kalikot",
  "Mugu",
  "Salyan",
  "Surkhet",
  "Achham",
  "Baitadi",
  "Bajhang",
  "Bajura",
  "Dadeldhura",
  "Darchula",
  "Doti",
  "Kailali",
  "Kanchanpur",
];

export const cities = NEPAL_CITIES.map((city) => city.toLowerCase());

export const INDUSTRY_LABELS: Record<string, string> = {
  "restaurant": "Restaurant",
  "ecommerce": "E-commerce",
  "clothing": "Clothing Store",
  "school-college": "School & College",
  "medical-clinic": "Medical Clinic",
  "travel-tours": "Travel & Tours",
  "gym-fitness": "Gym & Fitness",
  "real-estate": "Real Estate",
  "beauty-salon": "Beauty Salon",
  "grocery": "Grocery Store",
  "educational-consultancy": "Educational Consultancy",
  "digital-agency": "Digital Agency",
  "dental-clinic": "Dental Clinic",
  "booking-service": "Booking & Services",
  "website-developer": "Website Developer",
};

export interface IndustryContent {
  title: string;
  description: string;
  benefits: string[];
  features: { title: string; description: string }[];
  faqs: { question: string; answer: string }[];
}

export function getIndustryContent(category: string, cityName: string): IndustryContent {
  const cityNameCap = cityName.charAt(0).toUpperCase() + cityName.slice(1);
  const label = INDUSTRY_LABELS[category] || "Business";

  return {
    title: `Premium ${label} Web Design & Development in ${cityNameCap}, Nepal`,
    description: `Get a premium, high-speed ${label.toLowerCase()} website in ${cityNameCap} designed to rank on Google. Features local payment gateways (eSewa, Khalti), instant booking, and dynamic layouts built by Bibek Bhattarai.`,
    benefits: [
      `Local SEO configuration targeting ${cityNameCap} search terms.`,
      `Zero-lag page loads leveraging Next.js static generation.`,
      `Integrated Nepalese payment systems (eSewa, Khalti, Fonepay).`,
      `Sleek, responsive dark/light mode interfaces tailored to your brand.`,
    ],
    features: [
      {
        title: "Localized Search Engine Dominance",
        description: `Your ${label.toLowerCase()} site will be optimized for local search queries in ${cityNameCap} (e.g. "best ${label.toLowerCase()} in ${cityNameCap}") to attract walk-in and online customers directly.`,
      },
      {
        title: "Nepalese Payment Integrations",
        description: "Seamless checkout experiences with native integration for eSewa, Khalti, Fonepay, and mobile banking transfers, ensuring easy transactions for your clients.",
      },
      {
        title: "Blazing Fast Core Web Vitals",
        description: "Slow websites lose sales. Built on Next.js 15 and server components, your site will load in under a second, ranking higher on Google and keeping users engaged.",
      },
    ],
    faqs: [
      {
        question: `How long does it take to launch a ${label.toLowerCase()} website in ${cityNameCap}?`,
        answer: "Typically, a complete website is built, polished, and launched within 2 to 3 weeks depending on custom integrations and content volume.",
      },
      {
        question: "Can I manage the website content myself without knowing code?",
        answer: "Yes. I build sites with admin dashboards (or modular markdown/CMS settings) so you can easily edit text, add images, and post blogs without touch a single line of code.",
      },
      {
        question: `Why choose a Next.js web developer in ${cityNameCap} over standard WordPress?`,
        answer: "Next.js sites compile to static files, making them virtually unhackable, 5x faster than WordPress, and significantly better at SEO out-of-the-box since there are no heavy database query delays.",
      },
    ],
  };
}
